# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 381, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_v_main_window = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_v_main_window.setContentsMargins(10, 10, 10, 10)
        self.layout_v_main_window.setObjectName("layout_v_main_window")
        self.groupBox_control_panel = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_control_panel.sizePolicy().hasHeightForWidth())
        self.groupBox_control_panel.setSizePolicy(sizePolicy)
        self.groupBox_control_panel.setMinimumSize(QtCore.QSize(50, 95))
        self.groupBox_control_panel.setObjectName("groupBox_control_panel")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_control_panel)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 361, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_v_control_panel = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_v_control_panel.setContentsMargins(5, 0, 5, 5)
        self.layout_v_control_panel.setObjectName("layout_v_control_panel")
        self.layout_h_url = QtWidgets.QHBoxLayout()
        self.layout_h_url.setContentsMargins(10, 5, 10, 5)
        self.layout_h_url.setObjectName("layout_h_url")
        self.label_url = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_url.setObjectName("label_url")
        self.layout_h_url.addWidget(self.label_url)
        self.lineEdit_url = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.layout_h_url.addWidget(self.lineEdit_url)
        self.layout_v_control_panel.addLayout(self.layout_h_url)
        self.line_control_panel = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_control_panel.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_control_panel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_control_panel.setObjectName("line_control_panel")
        self.layout_v_control_panel.addWidget(self.line_control_panel)
        self.pushButton_retrieve_document = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_retrieve_document.setObjectName("pushButton_retrieve_document")
        self.layout_v_control_panel.addWidget(self.pushButton_retrieve_document)
        self.layout_v_main_window.addWidget(self.groupBox_control_panel)
        self.line_main_window = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_main_window.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_main_window.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_main_window.setObjectName("line_main_window")
        self.layout_v_main_window.addWidget(self.line_main_window)
        self.textBrowser_viewer = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_viewer.sizePolicy().hasHeightForWidth())
        self.textBrowser_viewer.setSizePolicy(sizePolicy)
        self.textBrowser_viewer.setOpenExternalLinks(True)
        self.textBrowser_viewer.setObjectName("textBrowser_viewer")
        self.layout_v_main_window.addWidget(self.textBrowser_viewer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Unified Document Reader"))
        self.groupBox_control_panel.setTitle(_translate("MainWindow", "Control Panel"))
        self.label_url.setText(_translate("MainWindow", "URL"))
        self.pushButton_retrieve_document.setText(_translate("MainWindow", "Retrieve Document"))
        self.textBrowser_viewer.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:6.85714pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6.85714pt;\">File Name: NYI</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6.85714pt;\">File URL: N/A</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6.85714pt;\">-------------</span></p></body></html>"))
